apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.2.2
  name: opentelemetry-demo-grafana-test
  namespace: otel-demo
