apiVersion: v1
data:
  run.sh: "@test \"Test Health\" {\n  url=\"http://opentelemetry-demo-grafana/api/health\"\
    \n\n  code=$(wget --server-response --spider --timeout 90 --tries 10 ${url} 2>&1\
    \ | awk '/^  HTTP/{print $2}')\n  [ \"$code\" == \"200\" ]\n}"
kind: ConfigMap
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.2.2
  name: opentelemetry-demo-grafana-test
  namespace: otel-demo
