apiVersion: v1
kind: Pod
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.2.2
  name: opentelemetry-demo-grafana-test
  namespace: otel-demo
spec:
  containers:
  - command:
    - /opt/bats/bin/bats
    - -t
    - /tests/run.sh
    image: docker.io/bats/bats:v1.4.1
    imagePullPolicy: IfNotPresent
    name: opentelemetry-demo-test
    volumeMounts:
    - mountPath: /tests
      name: tests
      readOnly: true
  restartPolicy: Never
  serviceAccountName: opentelemetry-demo-grafana-test
  volumes:
  - configMap:
      name: opentelemetry-demo-grafana-test
    name: tests
